
model:
  psz: 11
  model_fname: "models/feb402psz11.pth"

frame:
  dark_h5: null
  min_intensity: 0
  offset_recover: 30 # a[a>0] += 
  pvkey: "GE5:Pva1:Image"
  nproc: 4 # number of processes for frame preproc
  max_radius: 1000
  min_peak_sz: 3 # minimum number of non-pixel
  datatype: "ushortValue" # only if data are not compressed
  
infer:
  tensorrt: True
  mbsz: 32 

output:
  frame2file: "/net/wolf/data/users/zhengchun.liu/frames.h5"
  peaks2file: "/net/wolf/data/users/zhengchun.liu/peaks.h5"
  port4zmq: 5678
